config/routes.rb
Rails.application.routes.draw do
  get 'memberships/login'

  get 'memberships/signup'
  get 'memberships/modify'

  post 'memberships/signup_handle'

  get 'login/index'

  get 'article/new'

  get 'articles/modify'
  post 'articles/modify'
  get 'articles/edt'
  post 'articles/edt_handle'

  get 'notices/modify'
  post 'notices/modify'
  get 'notices/edt'
  post 'notices/edt_handle'

  get  'projects/modify'
  post 'projects/modify'
  get 'projects/edt'
  post 'projects/edt_handle'
  get 'projects/add_status'
  post 'projects/add_status_handle'
  get 'projects/add_members'
  post 'projects/add_members'
  get 'projects/my_projects'

  get 'article/_nav'

  get 'welcome/_nav'

  get 'welcome/nav'
  get 'welcome/error'

  get 'welcome/project'

  get 'welcome/notice'

  get 'welcome/notice'

  get 'welcome/article'

  get 'welcome/index'

  get 'welcome/about_us'

  root 'welcome#index'

  resources :articles
  resources :notices
  resources :projects
  resources :memberships
  resources :member

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  def Notice.insert(title, text, admin_name)
    @a = Notice.new
    @a.title = title
    @a.content = text
    @a.admin_id = admin_name
    @a.save!
  end
  def Notice.find_by_id(id)
    @a = Notice.all
    @a.each do |r|
      if r.id == id
        return r
      end
    end
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  def new
    if session[:ut] != 'admin'
      redirect_to welcome_error_path
    end
  end
  def create
    redirect_to :notices

    @title = params[:notice][:title]
    @text  = params[:notice][:text]
    @admin_name = session[:un]
    # puts  @title, @text
    Notice.insert(@title, @text, @admin_name)
  end

  def index
    @notices = Notice.all.reverse_order
  end

  def show
    id = params[:id].to_i
    # puts id
    if id == 1
      puts '11'
    end
    @notice = Notice.find_by_id(id)
  end

  def modify
    if session[:ut] != 'admin'
      redirect_to welcome_error_path
    end

    @notices = Notice.all
    # delete a notice
    if params[:del]
      @del_id = params[:del]
      Notice.delete(@del_id)
    end
    # edit a notice
    if params[:edt]
      @edt_id = params[:edt]
      # redirect_to
    end
  end

  # get notice edit page
  def edt
    if session[:ut] != 'admin'
      redirect_to welcome_error_path
    end

    @edt_id = params[:edt]
    session[:edt_id] = @edt_id
    @notice = Notice.find(@edt_id)

  end

  def edt_handle
    # handle notice edit post request
    if params[:notices_edt][:title]
      Notice.update(session[:edt_id], :title=>params[:notices_edt][:title],
                     :content => params[:notices_edt][:text])

      redirect_to notices_modify_path
    end
  end
  def del
    @notices = Notice.all
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/edt.html.erb
<%= render '/welcome/nav'%>

<div class="container" style="min-height: 390px">
  <h2 align="center">编辑</h2>
  <div class="toMiddle" style="height: 4px;margin-bottom: 10px;margin-top: -5px"></div>
  <div style="width: 95%;float: right;margin-right: 2.5%">
    <ul class="nav nav-tabs nav-justified">
      <li role="presentation"><a href="">项目</a></li>
      <li role="presentation"><a href="../articles/modify">文章</a></li>
      <li role="presentation" class="active"><a href="../notices/modify">通知</a></li>
    </ul>
    <div style="width:100%; border: solid #ddd 1px;border-top: none;height: 500px">
      <%= form_for :notices_edt, url: :notices_edt_handle do |f| %>
          <div class="panel-body">
            <form class="form-horizontal" role="form">
              <div class="form-group">
                <label class="col-sm-1 control-label">标题</label>
                <div class="col-sm-11">
                  <%= f.text_field  :title, :value => @notice.title, class: 'form-control'%>
                </div>
              </div>
              <div class="form-group" style="clear: both">
                <label class="col-sm-1 control-label text-top">正文</label>
                <div class="col-sm-11" style="margin-top: 10px">
                  <%= f.text_area  :text, :value => @notice.content , rows:15, class: 'form-control'%>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-12" align="right" style="margin-top: 3%;padding-left: 50%">
                  <%= f.submit('保存修改', class:'btn btn-success btn-sm') %>
                </div>
              </div>
            </form>
          </div>
      <%end%>
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/notices/index.html.erb
<%= render '/welcome/nav'%>

<div class="container">
  <h3 align="center">通知列表</h3>
  <div style="margin-bottom: 5px">
    <ol class="breadcrumb">
      <li><a href="/">主页</a></li>
      <li class="active">项目</li>
    </ol>
  </div>
  <div class="toLeft" style="height: 4px;margin-top: -10px"></div>
  <div class="row">
    <div class="col-xs-12">
      <table class="table index-show" style="margin-bottom: 10px !important;">
        <thead style="">
        <tr style="line-span: 3">
          <th style="width: 60%">通知</th>
          <th style="text-align: right; width: 30%">发布日期</th>
        </tr>
        </thead>
      </table>
      <hr style="border:none;border-top:2px dotted rgba(135, 135, 135, 1);margin-bottom: 3px;margin-top: -10px">
      <table class="table index-show table-hover bg-warning">
        <tbody>
        <% @i = 0 %>
        <% @notices.each do |a| %>
            <tr>
                <% @i = a.id %>
                <%params[:id] = @i%>
              <td style="width: 60%">
                <%= link_to a[:title], notices_path + '/' + @i.to_s %>
              </td>
              <td style="text-align: right; width: 30%">
                <%= a[:created_at]%>
              </td>
            </tr>

        <% end %>
        </tbody>
      </table>
      <hr style="border:none;border-top:2px solid black;margin-bottom: 3px;margin-top: -20px">
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/notices/modify.html.erb
<%= render '/welcome/nav'%>

<div class="container">
  <h2>修改通知</h2>
  <div class="toRight" style="height: 4px"></div>
  <div class="row">
    <div class="col-xs-12">
      <table class="table index-show table-hover" style="vertical-align: middle">
        <tbody>
          <% @notices.each do |r|%>
            <tr class="bg-warning">
              <td style="width: 65%">
                <strong>&bull;&nbsp;</strong><%= r.title %>
              </td>
              <td style="width: 25%">
                <%= r.updated_at%>
              </td>
              <td style="text-align: center; width: 5%;text-decoration: underline" class="article-modify">
                <%= link_to '编辑', notices_edt_path+'?'+'edt='+r.id.to_s%>
              </td>
              <td style="text-align: center; width: 5%;text-decoration: underline" class="article-modify">
                <%= link_to '删除', notices_modify_path+'?'+'del='+r.id.to_s%>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/notices/new.html.erb
<%= render '/welcome/nav'%>

<div class="container" style="min-height: 390px">
  <h2 align="center">发布</h2>
  <div class="toMiddle" style="height: 4px;margin-bottom: 10px;margin-top: -5px"></div>
  <div style="width: 95%;float: right;margin-right: 2.5%">
    <ul class="nav nav-tabs nav-justified">
      <li role="presentation"><a href="../projects/new">项目</a></li>
      <li role="presentation"><a href="../articles/new">文章</a></li>
      <li role="presentation" class="active"><a href="../notices/new">通知</a></li>
    </ul>
    <div style="width:100%; border: solid #ddd 1px;border-top: none;height: 500px">
      <%= form_for :notice, url: :notices do |f| %>
        <div class="panel-body">
          <form class="form-horizontal" role="form">
            <div class="form-group">
              <label class="col-sm-1 control-label">标题</label>
              <div class="col-sm-11">
                <%= f.text_field(:title, class: 'form-control')%>
              </div>
            </div>
            <div class="form-group" style="clear: both">
              <label class="col-sm-1 control-label text-top">正文</label>
              <div class="col-sm-11" style="margin-top: 10px">
                <%= f.text_area(:text, rows:15, class: 'form-control')%>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-12" align="right" style="margin-top: 3%;padding-left: 50%">
                <%= f.submit('保存通知', class:'btn btn-success btn-sm') %>
              </div>
            </div>
          </form>
        </div>
      <%end%>
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/notices/show.html.erb
<%= render '/welcome/nav'%>

<div class="container" style="min-height: 390px">
  <ol class="breadcrumb">
    <li><a href="/">主页</a></li>
    <li><a href="/notices">通知列表</a></li>
    <li class="active"><%= @notice[:title]%></li>
  </ol>
  <div align="center">
    <h1>
      <%= @notice[:title]%>
    </h1>
  </div>
  <div align="right">
    <label class="show-date">
      创建日期:
      <%= @notice[:release_date] %><br>
      浏览量:
    </label>
  </div>
  <div>
    <p style="text-indent: 0">
      <%= @notice[:content]%>
    </p>
  </div>
</div>

<%= render 'welcome/footer' %>