config/routes.rb
Rails.application.routes.draw do
  get 'memberships/login'

  get 'memberships/signup'
  get 'memberships/modify'

  post 'memberships/signup_handle'

  get 'login/index'

  get 'article/new'

  get 'articles/modify'
  post 'articles/modify'
  get 'articles/edt'
  post 'articles/edt_handle'

  get 'notices/modify'
  post 'notices/modify'
  get 'notices/edt'
  post 'notices/edt_handle'

  get  'projects/modify'
  post 'projects/modify'
  get 'projects/edt'
  post 'projects/edt_handle'
  get 'projects/add_status'
  post 'projects/add_status_handle'
  get 'projects/add_members'
  post 'projects/add_members'
  get 'projects/my_projects'

  get 'article/_nav'

  get 'welcome/_nav'

  get 'welcome/nav'
  get 'welcome/error'

  get 'welcome/project'

  get 'welcome/notice'

  get 'welcome/notice'

  get 'welcome/article'

  get 'welcome/index'

  get 'welcome/about_us'

  root 'welcome#index'

  resources :articles
  resources :notices
  resources :projects
  resources :memberships
  resources :member

end

app/models/article.rb
class Article < ActiveRecord::Base

  def Article.images_path
    @a = "/assets/images/"
    return @a
  end
  def Article.insert(title, text, admin_name)
    @a = Article.new
    @a.title = title
    @a.content = text
    @a.admin_id = admin_name
    @a.save!
  end
  def Article.find_by_id(id)
    @a = Article.all
    @a.each do |r|
      if r.id == id
        return r
      end
    end
  end
  def Article.delete_by_id(id)
  end

  def Article.find_by_title(title)
    @a = Article.find_by_sql("select id from articles where title = '#{title}'").first.id
    return @a
  end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def new
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  protected
  def uploadfile(file)
    if !file.original_filename.empty?
      @filename = file.original_filename
      #设置目录路径，如果目录不存在，生成新目录
      FileUtils.mkdir("#{Rails.root}/app/assets/images") unless File.exist?("#{Rails.root}/app/assets/images")
      #写入文件
      ##wb 表示通过二进制方式写，可以保证文件不损坏
      File.open("#{Rails.root}/app/assets/images/#{@filename}", "wb") do |f|
        f.write(file.read)
      end
      return @filename
    end
  end
  public
# get
  def new
    if session[:ut] != 'admin'
      redirect_to welcome_error_path
    end
  end
# post
  def create
    redirect_to :articles

    @title = params[:article][:title]
    @text  = params[:article][:text]
    @admin_name = session[:un]


    Article.insert(@title, @text, @admin_name)

    if params[:article][:image]
      @id_just_gen = Article.find_by_title(@title)
      # put image into Image
      @image_file_name = uploadfile(params[:article][:image])
      # puts "----------------------"
      # puts @image_file_name
      # puts "----------------------"
      # put  @title, @text into Article
      Image.insert(@id_just_gen, @image_file_name)
    end
  end

  def index
    @articles = Article.all.reverse_order
  end

  def show
    id = params[:id].to_i
    # puts id
    if id == 1
      puts '11'
    end
    @article = Article.find_by_id(id)
    @image_path = Image.find_by_sql("select * from images where article_id = #{id}").first
    if @image_path
      @image_path = @image_path.image_path
    end
    puts @image_path
  end

  def modify
    if session[:ut] != 'admin'
      redirect_to welcome_error_path
    end

    @articles = Article.all
    # delete an article
    if params[:del]
      @del_id = params[:del]
      Article.delete(@del_id)
    end
    # edit an article
    if params[:edt]
      @edt_id = params[:edt]
      # redirect_to
    end
  end

  # get article edit page
  def edt
    if session[:ut] != 'admin'
      redirect_to welcome_error_path
    end

    @edt_id = params[:edt]
    session[:edt_id] = @edt_id
    @article = Article.find(@edt_id)

  end

  def edt_handle
    # handle article edit post request
    if params[:articles_edt][:title]
      Article.update(session[:edt_id], :title=>params[:articles_edt][:title],
      :content => params[:articles_edt][:text])

      redirect_to articles_modify_path
    end
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edt.html.erb
<%= render '/welcome/nav'%>

<div class="container" style="min-height: 390px">
  <h2 align="center">编辑</h2>
  <div class="toMiddle" style="height: 4px;margin-bottom: 10px;margin-top: -5px"></div>
  <div style="width: 95%;float: right;margin-right: 2.5%">
    <ul class="nav nav-tabs nav-justified">
      <li role="presentation"><a href="">项目</a></li>
      <li role="presentation" class="active"><a href="../articles/modify">文章</a></li>
      <li role="presentation"><a href="../notices/modify">通知</a></li>
    </ul>
    <div style="width:100%; border: solid #ddd 1px;border-top: none;height: 500px">
      <%= form_for :articles_edt, url: :articles_edt_handle do |f| %>
          <div class="panel-body">
            <form class="form-horizontal" role="form">
              <div class="form-group">
                <label class="col-sm-1 control-label">标题</label>
                <div class="col-sm-11">
                  <%= f.text_field  :title, :value => @article.title ,class: 'form-control' %>
                </div>
              </div>
              <div class="form-group" style="clear: both">
                <label class="col-sm-1 control-label text-top">正文</label>
                <div class="col-sm-11" style="margin-top: 10px">
                  <%= f.text_area  :text, :value => @article.content, rows:15, class: 'form-control' %>
                </div>
              </div>
              <div class="form-group" style="clear: both">
                <label class="col-sm-1 control-label text-top">图片</label>
                <div class="col-sm-11" style="margin-top: 15px">
                  <%= f.file_field(:image)%>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-12" align="right" style="margin-top: 3%;padding-left: 50%">
                  <%= f.submit('保存修改', class:'btn btn-success btn-sm') %>
                </div>
              </div>
            </form>
          </div>
      <%end%>
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/articles/index.html.erb
<%= render '/welcome/nav'%>

<div class="container">
  <h3 align="center">相关报道列表</h3>
  <div style="margin-bottom: 5px">
    <ol class="breadcrumb">
      <li><a href="/">主页</a></li>
      <li class="active">相关报道</li>
    </ol>
  </div>
  <div class="toRight" style="height: 4px;margin-top: -10px"></div>
  <div class="row">
    <div class="col-xs-12">
      <table class="table index-show" style="margin-bottom: 10px !important;">
        <thead style="">
        <tr style="line-span: 3">
          <th style="width: 65%">报道</th>
          <th style="text-align: right; width: 25%">发布日期</th>
        </tr>
        </thead>
      </table>
      <hr style="border:none;border-top:2px dotted rgba(135, 135, 135, 1);margin-bottom: 3px;margin-top: -10px">
      <table class="table index-show table-hover bg-warning">
        <tbody>
        <% @i = 0 %>
        <% @articles.each do |a| %>
            <tr>
                <% @i = a.id %>
                <%   params[:id] = @i %>
              <td style="width: 65%">
                <%= link_to a[:title], articles_path + '/' + @i.to_s %>
              </td>
              <td style="text-align: right; width: 25%">
                <%= a.updated_at%>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <hr style="border:none;border-top:2px solid black;margin-bottom: 3px;margin-top: -20px">
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/articles/modify.html.erb
<%= render '/welcome/nav'%>

<div class="container">
  <h2>修改相关报道</h2>
  <div class="toRight" style="height: 4px"></div>
  <div class="row">
    <div class="col-xs-12">
      <table class="table index-show table-hover" style="vertical-align: middle">
        <tbody>
        <% @i = 0 %>
        <% @articles.each do |a| %>
            <tr class="bg-warning">
                <% @i = a.id %>
                <%   params[:id] = @i %>
              <td style="width: 80%">
                <strong>&bull;&nbsp;</strong><%= link_to a[:title], articles_path + '/' + @i.to_s%>
              </td>
              <td style="text-align: center; width: 5%;text-decoration: underline" class="article-modify">
                <%= link_to '编辑', articles_edt_path+'?'+'edt='+a.id.to_s%>
              </td>
              <td style="text-align: center; width: 5%;text-decoration: underline" class="article-modify">
                <%= link_to '删除', articles_modify_path+'?'+'del='+a.id.to_s%>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/articles/new.html.erb
<%= render '/welcome/nav'%>

<div class="container" style="min-height: 390px">
  <h2 align="center">发布</h2>
  <div class="toMiddle" style="height: 4px;margin-bottom: 10px;margin-top: -5px"></div>
  <div style="width: 95%;float: right;margin-right: 2.5%">
    <ul class="nav nav-tabs nav-justified">
      <li role="presentation"><a href="../projects/new">项目</a></li>
      <li role="presentation" class="active"><a href="../articles/new">文章</a></li>
      <li role="presentation"><a href="../notices/new">通知</a></li>
    </ul>
    <div style="width:100%; border: solid #ddd 1px;border-top: none;height: 500px">
      <%= form_for :article, url: :articles do |f| %>
        <div class="panel-body">
          <form class="form-horizontal" role="form">
            <div class="form-group">
              <label class="col-sm-1 control-label">标题</label>
              <div class="col-sm-11">
                <%= f.text_field(:title, class: 'form-control')%>
              </div>
            </div>
            <div class="form-group" style="clear: both">
              <label class="col-sm-1 control-label text-top">正文</label>
              <div class="col-sm-11" style="margin-top: 10px">
                <%= f.text_area(:text, rows:15, class: 'form-control')%>
              </div>
            </div>
            <div class="form-group" style="clear: both">
              <label class="col-sm-1 control-label text-top">图片</label>
              <div class="col-sm-11" style="margin-top: 15px">
                <%= f.file_field(:image)%>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-12" align="right" style="margin-top: 3%;padding-left: 50%">
                <%= f.submit('保存文章', class:'btn btn-success btn-sm') %>
              </div>
            </div>
          </form>
        </div>
      <%end%>
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/articles/show.html.erb
<%= render '/welcome/nav'%>

<div class="container" style="min-height: 390px">
  <ol class="breadcrumb">
    <li><a href="/">主页</a></li>
    <li><a href="/articles">相关报道列表</a></li>
    <li class="active"><%= @article[:title]%></li>
  </ol>
  <div align="center">
    <h1>
      <%= @article[:title]%>
    </h1>
  </div>
  <div align="right">
    <label class="show-date">
      创建日期:<%= %><br>浏览量:
    </label>
  </div>
  <div>
    <p>
      <%= @article[:content]%>
    </p>
    <% if @image_path%>
        <p>
          <%= image_tag(@image_path)%>
        </p>
    <% end%>
  </div>
</div>

<%= render 'welcome/footer' %>