config/routes.rb
Rails.application.routes.draw do
  get 'memberships/login'

  get 'memberships/signup'
  get 'memberships/modify'

  post 'memberships/signup_handle'

  get 'login/index'

  get 'article/new'

  get 'articles/modify'
  post 'articles/modify'
  get 'articles/edt'
  post 'articles/edt_handle'

  get 'notices/modify'
  post 'notices/modify'
  get 'notices/edt'
  post 'notices/edt_handle'

  get  'projects/modify'
  post 'projects/modify'
  get 'projects/edt'
  post 'projects/edt_handle'
  get 'projects/add_status'
  post 'projects/add_status_handle'
  get 'projects/add_members'
  post 'projects/add_members'
  get 'projects/my_projects'

  get 'article/_nav'

  get 'welcome/_nav'

  get 'welcome/nav'
  get 'welcome/error'

  get 'welcome/project'

  get 'welcome/notice'

  get 'welcome/notice'

  get 'welcome/article'

  get 'welcome/index'

  get 'welcome/about_us'

  root 'welcome#index'

  resources :articles
  resources :notices
  resources :projects
  resources :memberships
  resources :member

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def _nav
  end
  def error
  end
  def index
    @articles = Article.all.reverse_order
    @notices  = Notice.all.reverse_order
    @projects = Project.all.reverse_order
    if params[:operation] == 'log_out'
      session[:ut] = nil
      session[:un] = nil
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_footer.html.erb
<div class="footer">
  <div class="container">
    <table>
      <tr>
        <td><a href="http://www.ucas.ac.cn/">国科大官网</a></td>
        <td><a href="https://github.com/teamshow/team_show">我们的Github</a></td>
        <td><a href="http://apache.opencas.org/">科技网镜像站</a></td>
      </tr>
    </table>
    <p>制作人：陈立国 许柏宁 杨海华    地址：中国科学院大学雁栖湖校区       联系方式：1234567890123    010-12345678</p>
  </div>
  <!--<div class="container" style="vertical-align: bottom;">-->
    <!--制作人：XXX XXX XXX      地址：中国科学院大学雁栖湖校区       联系方式：1234567890123    010-12345678-->
  <!--</div>-->
</div>

app/views/welcome/_nav.html.erb
<div class="page-header" align="center" >
  <div style="padding-top: 5px; padding-right: 5px;font-size: 12px;vertical-align: middle;font-weight: bold;color: white !important;" align="right">
    <% if session[:ut]==nil%>
        <a href="../memberships/login" class="btn btn-primary btn-xs" role="button">登&nbsp&nbsp&nbsp&nbsp&nbsp陆</a>
        <a href="../memberships/signup" class="btn btn-primary btn-xs" role="button">注&nbsp&nbsp&nbsp&nbsp&nbsp册</a>
    <% else if session[:ut]=="admin" %>
        欢迎您, <%= session[:un] %>
        <div class="btn-group btn-xs" style="width: 10% !important;">
          <button type="button" class="btn btn-primary" style="width: 80% !important;padding: 1px 5px 1px 10px !important;font-size: 12px !important;">
            操&nbsp&nbsp&nbsp&nbsp&nbsp作
          </button>
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" style="font-size: 12px !important;padding: 1px 5px !important;width: 20% !important;" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            <li class="dropdown-submenu">
              <a tabindex="-1" href="../articles/new">发布</a>
              <ul class="dropdown-menu">
                <li><a href="../projects/new">项目</a></li>
                <li><a href="../articles/new">相关报道</a></li>
                <li><a href="../notices/new">通知</a></li>
              </ul>
            </li>
            <li class="dropdown-submenu">
              <a tabindex="-1" href="../articles/modify">修改</a>
              <ul class="dropdown-menu">
                <li><a href="../projects/modify">项目</a></li>
                <li><a href="../articles/modify">相关报道</a></li>
                <li><a href="../notices/modify">通知</a></li>
                <li><a href="../memberships/modify">成员</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <button onclick="window.location.href='/?operation=log_out'" class="btn btn-primary btn-xs" style="margin-left: 10px">登&nbsp&nbsp&nbsp&nbsp&nbsp出</button>
    <% else%>
        欢迎您, <%= session[:un] %>
        <a href="../projects/my_projects" style="color: white;margin-left: 10px">我的项目</a>
        <button onclick="window.location.href='/?operation=log_out'" class="btn btn-primary btn-xs" style="margin-left: 10px">登&nbsp&nbsp&nbsp&nbsp&nbsp出</button>
    <%end%>
    <% end%>
  </div>
</div>
<nav class="navbar navbar-inverse" role="navigation">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav nav-pills nav-justified">
        <li><a href="/"><img alt="Brand" src="/assets/home_icon.png" height="20" width="20">主页</a></li>
        <li><a href="/projects">项目</a></li>
        <li><a href="/articles">相关报道</a></li>
        <li><a href="/notices">通知</a></li>
        <li><a href="/welcome/about_us">关于我们</a></li>
      </ul>
    </div>
</nav>

app/views/welcome/about_us.html.erb
<%= render '/welcome/nav' %>

<div class="container">
  <h3>关于我们</h3>
  <div class="toMiddle" style="height: 4px;margin-top: -10px"></div>
  <h4 style="margin-top: 20px;text-align: center;font-weight: bolder;font-size: 20px">团队网站</h4>
  <p style="text-indent: 2em">成员：陈立国、许柏宁、杨海华。</p>
  <p style="margin-top: 50px;text-align: right">欢迎联系我们</p>
</div>

<%= render 'welcome/footer' %>

app/views/welcome/article.html.erb
<%= render 'nav'%>

<h1>Welcome#article</h1>
<p>Find me in app/views/welcome/article.html.erb</p>

app/views/welcome/error.html.erb
<h1>error</h1>
<p>You didn't have the permission to access that page.</p>

app/views/welcome/index.html.erb
<%= render '/welcome/nav' %>

<div class="container" style="min-height: 100%">
  <div class="row">
    <div class="row">
      <div class="row">
        <div class="col-xs-7">
          <table class="table">
            <tr>
              <th>项目</th>
              <th style="text-align: right"><a href="/projects">+ 更多</a></th>
            </tr>
          </table>
          <div class="toRight" style="height: 4px;margin-top: -28px"></div>
          <table class="table table-hover index-show">
            <% @i = 0 %>
            <% @projects.each do |r| %>
                <%
                  params[:id] = r.id

                  if @i > 5
                    break
                  end
                  @i += 1
                  puts "#{r}"
                %>
                <tr>
                  <td><%= link_to r.name, projects_path + '/' + r.id.to_s %></td>
                </tr>
            <% end %>

          </table>
        </div>
      <div class="col-xs-5">
        <table class="table">
          <tr>
            <th>通知</th>
            <th style="text-align: right"><a href="/notices">+ 更多</a></th>
          </tr>
        </table>
        <div class="toLeft" style="height: 4px;margin-top: -28px"></div>
        <table class="table table-hover index-show">
          <% @i = 0 %>
          <% @notices.each do |r| %>
              <%
                 params[:id] = r.id
                 if @i > 5
                   break
                 end
                 @i += 1
                 puts "#{r}"
              %>
              <tr>
                <td><%= link_to r.title, notices_path + '/' + r.id.to_s %></td>
                <td class="index-date"><%= r[:created_at] %></td>
              </tr>
          <% end %>
        </table>
      </div>
    </div>
      <div class="col-xs-7">
        <table class="table">
          <tr>
            <th>相关报道</th>
            <th style="text-align: right"><a href="/articles">+ 更多</a></th>
          </tr>
        </table>
        <div class="toRight" style="height: 4px;margin-top: -28px"></div>
        <table class="table table-hover index-show">
          <% @i = 0 %>
          <% @articles.each do |r| %>
              <%
                params[:id] = r.id
                if @i > 5
                  break
                end
                @i += 1
                puts "#{r}"
              %>
              <tr>
                <td><%= link_to r.title, articles_path + '/' + r.id.to_s %></td>
                <td class="index-date"><%= r[:created_at] %></td>
              </tr>
          <% end %>
        </table>

      </div>
      <div class="col-xs-5">
        <table class="table">
          <tr>
            <th>关于我们</th>
            <!--<th style="text-align: right"><a href="/projects">+ more</a></th>-->
          </tr>
        </table>
        <div class="toLeft" style="height: 4px;margin-top: -28px"></div>
        <table class="table table-hover index-show">
          <td>
            <h4 style="text-align: center;font-weight: bolder;font-size: 20px">团队网站</h4>
            <p style="text-indent: 2em">成员：陈立国、许柏宁、杨海华。</p>
            <p style="margin-top: 40px;text-align: right">欢迎联系我们</p>
            </td>
        </table>
      </div>
    </div>
  </div>
</div>

<%= render 'footer' %>

app/views/welcome/notice.html.erb
<%= render 'nav'%>

<h1>Welcome#notice</h1>
<p>Find me in app/views/welcome/notice.html.erb</p>

app/views/welcome/project.html.erb
<%= render 'nav'%>

<h1>Welcome#project</h1>
<p>Find me in app/views/welcome/project.html.erb</p>