config/routes.rb
Rails.application.routes.draw do
  get 'memberships/login'

  get 'memberships/signup'
  get 'memberships/modify'

  post 'memberships/signup_handle'

  get 'login/index'

  get 'article/new'

  get 'articles/modify'
  post 'articles/modify'
  get 'articles/edt'
  post 'articles/edt_handle'

  get 'notices/modify'
  post 'notices/modify'
  get 'notices/edt'
  post 'notices/edt_handle'

  get  'projects/modify'
  post 'projects/modify'
  get 'projects/edt'
  post 'projects/edt_handle'
  get 'projects/add_status'
  post 'projects/add_status_handle'
  get 'projects/add_members'
  post 'projects/add_members'
  get 'projects/my_projects'

  get 'article/_nav'

  get 'welcome/_nav'

  get 'welcome/nav'
  get 'welcome/error'

  get 'welcome/project'

  get 'welcome/notice'

  get 'welcome/notice'

  get 'welcome/article'

  get 'welcome/index'

  get 'welcome/about_us'

  root 'welcome#index'

  resources :articles
  resources :notices
  resources :projects
  resources :memberships
  resources :member

end

app/models/project.rb
class Project < ActiveRecord::Base

  def Project.insert(title, text)
    @a = Project.new
    @a.name = title
    @a.description = text
    @a.save!
  end

  def Project.find_by_id(id)
    @a = Project.all
    @a.each do |r|
      if r.id == id
        return r
      end
    end
  end

  def Project.find_by_member_id(id)
    @ret = Project.find_by_sql("select projects.id,projects.name,projects.description from belongs,members,projects where projects.id = belongs.project_id and belongs.member_id = members.id and belongs.member_id = #{id}")
    return @ret
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    if session[:ut] != 'admin'
      redirect_to welcome_error_path
    end
  end

  def create
    redirect_to :projects

    @title = params[:project][:title]
    @text = params[:project][:text]
    # puts  @title, @text
    Project.insert(@title, @text)

  end

  def index
    @projects = Project.all.reverse_order
    @status = Status.find_by_sql("select * from statuses where 1=1 group by project_id order by created_at desc")

    @status_dict = {}
    @projects.each do |p|
      @status.each do |s|
        if p.id == s.project_id
          @status_dict[p.id] = s.status
        end
      end
    end
  end

  def show
    id = params[:id].to_i
    @project = Project.find_by_id(id)
    @members = Belong.find_by_project_id(id)
  end

  def modify
    if session[:ut] != 'admin'
      redirect_to welcome_error_path
    end

    @projects = Project.all
    # delete a project
    if params[:del]
      @del_id = params[:del]
      Project.delete(@del_id)
      Status.delete_by_project_id(@del_id)
    end
    # edit a project
    if params[:edt]
      @edt_id = params[:edt]
      # redirect_to
    end
  end

  # get project edit page
  def edt
    if session[:ut] != 'admin'
      redirect_to welcome_error_path
    end

    @edt_id = params[:edt]
    session[:edt_id] = @edt_id
    @project = Project.find(@edt_id)
    @status = Status.find_by_project_id(@edt_id.to_i)

    if params[:edt]
      session[:edt] = params[:edt]

      @members_added = Belong.find_by_project_id(params[:edt])
      @members_all = Member.all
      @map = {}

      # get map of whom are in group
      @members_all.each do |m|
        @members_added.each do |a|
          if m.name == a.name
            @map[m.id] = 'yes'
          end
        end
      end
      @projects_all = Project.all
      puts "#{@map}"
    end
  end

  def edt_handle
    # handle project edit post request
    if params[:projects_edt][:title]
      Project.update(session[:edt_id], :name => params[:projects_edt][:title],
                     :description => params[:projects_edt][:description])

      redirect_to projects_modify_path
    end
  end

  # get add_status page
  def add_status
    # request this page
    if params[:add]
      @add = params[:add]
      session[:add_id] = @add
    end
    # delete a status
    if params[:del_status_id]
      Status.delete(params[:del_status_id])
    end

    @status = Status.find_by_project_id(session[:add_id].to_i)
    @project_name = Project.find(session[:add_id]).name
    @projects_all = Project.all
  end

  # handle post status request.
  def add_status_handle

    Status.insert(session[:add_id], params[:status_add][:status])
    redirect_to projects_add_status_path + "?add=" +session[:add_id].to_s
  end

  # add members
  def add_members
    # get
    if params[:project_id]
      session[:project_id] = params[:project_id]

      @members_added = Belong.find_by_project_id(params[:project_id])
      @members_all = Member.all
      @map = {}

      # get map of whom are in group
      @members_all.each do |m|
         @members_added.each do |a|
           if m.name == a.name
             @map[m.id] = 'yes'
           end
         end
      end
      @projects_all = Project.all
      puts "#{@map}"
    end

    # post delete member
    if params[:del_member_id]
      Belong.delete_pair(params[:del_member_id], session[:project_id])
      redirect_to projects_add_members_path+'?project_id='+session[:project_id]
    end

    # post add member
    if params[:add_member_id]
      Belong.insert(params[:add_member_id], session[:project_id])
      redirect_to projects_add_members_path+'?project_id='+session[:project_id]
    end
  end

  # get user space
  def my_projects
    @member_id = Member.find_by_sql("select id from members where name = \'#{session[:un]}\'").first.id
    @my_projects = Project.find_by_member_id(@member_id)
    puts "#{@my_projects}"
  end

  def del
    @projects.all
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/add_members.html.erb
<%= render '/welcome/nav'%>


<div class="container" style="min-height: 390px">
  <h2 align="center">编辑</h2>
  <div class="toMiddle" style="height: 4px;margin-bottom: 10px;margin-top: -5px"></div>
  <div style="width: 95%;float: right;margin-right: 2.5%">
    <ul class="nav nav-tabs nav-justified">
      <li role="presentation" class="active"><a href="">项目</a></li>
      <li role="presentation"><a href="../articles/modify">文章</a></li>
      <li role="presentation"><a href="../notices/modify">通知</a></li>
    </ul>
    <div style="width:100%; border: solid #ddd 1px;border-top: none;height: 500px">
          <div class="panel-body">
            <form class="form-horizontal" role="form">
              <div style="float: left;width: 75%">
                <% @pid=session[:project_id] %>
                <% @projects_all.each do |project|%>
                  <% if project[:id].to_s==@pid %>
                    <div class="form-group" >
                      <label class="col-sm-2 control-label" style="padding-top: 0 !important">
                        标题
                      </label>
                      <div class="col-sm-10">
                        <textarea readonly rows="1" class="form-control"><%= project.name%></textarea>
                      </div>
                    </div>
                        <div class="form-group" style="clear: both">
                          <label class="col-sm-2 control-label" style="padding-top: 0 !important">
                            项目详情
                          </label>
                          <div class="col-sm-10">
                            <textarea readonly rows="15" class="form-control"><%= project.description%></textarea>
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-sm-12" align="right" style="margin-top: 3%;padding-left: 20%">
                            <%= link_to 'Edit this Project', projects_edt_path+'?'+'edt='+session[:project_id],class: 'btn btn-success btn-sm'%>
                          </div>
                        </div>
                    <% break %>
                  <%end%>
                <%end%>
              </div>
              <div style="float: left;width: 25%;padding-left: 2.5%;padding-right: 2.5%">
                <div class="panel panel-primary project-panel">
                  <div class="panel-heading" style="font-size: inherit !important;padding-top: 4px;padding-bottom: 4px">
                    <div class="panel-title" align="center" style="font-weight: bold">
                      Exiting Members
                    </div>
                  </div>
                  <div class="panel-body" style="padding: 5px;overflow-y: scroll;height: 150px !important">
                    <table class="table index-show table-hover">
                      <tbody>
                      <% @members_all.each do |m| %>
                          <% if @map[m.id] == 'yes' %>
                          <tr class="bg-warning">
                            <td style="width: 80%">
                              <%= m.name%>
                            </td>
                            <td style="vertical-align: middle;font-size:12px !important;text-align: center; width: 20%;text-decoration: underline" class="article-modify">
                              <%=link_to 'Delete', projects_add_members_path+'?del_member_id='+m[:id].to_s+'&project_id='+session[:project_id] %>
                            </td>
                          </tr>
                          <% end%>
                      <%end%>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="panel panel-primary project-panel" style="margin-top: 15px">
                  <div class="panel-heading" style="font-size: inherit !important;padding-top: 4px;padding-bottom: 4px">
                    <div class="panel-title" align="center" style="font-weight: bold">
                      Add Member
                    </div>
                  </div>
                  <div class="panel-body" style="padding: 5px;overflow-y: scroll;height: 150px !important">
                    <table class="table index-show table-hover">
                      <tbody>
                      <% @members_all.each do |m| %>
                          <% if @map[m.id] != 'yes' %>
                              <tr class="bg-warning">
                                <td style="width: 80%">
                                  <%= m.name%>
                                </td>
                                <td style="vertical-align: middle;font-size:12px !important;text-align: center; width: 20%;text-decoration: underline" class="article-modify">
                                  <%=link_to 'Add', projects_add_members_path+'?add_member_id='+m[:id].to_s+'&project_id='+session[:project_id] %>
                                </td>
                              </tr>
                          <% end%>
                      <%end%>
                      </tbody>
                    </table>
                  </div>
              </div>
              </div>
            </form>
          </div>
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/projects/add_status.html.erb
<%= render '/welcome/nav'%>
<div class="container" style="min-height: 390px">
  <h2 align="center">编辑</h2>
  <div class="toMiddle" style="height: 4px;margin-bottom: 10px;margin-top: -5px"></div>
  <div style="width: 95%;float: right;margin-right: 2.5%">
    <ul class="nav nav-tabs nav-justified">
      <li role="presentation" class="active"><a href="">项目</a></li>
      <li role="presentation"><a href="../articles/modify">文章</a></li>
      <li role="presentation"><a href="../notices/modify">通知</a></li>
    </ul>
    <div style="width:100%; border: solid #ddd 1px;border-top: none;height: 500px">
      <div class="panel-body">
        <form class="form-horizontal" role="form">
          <div style="float: left;width: 40%">
            <% @pid=session[:project_id] %>
            <% @projects_all.each do |project|%>
                <% if project[:id].to_s==@pid %>
                    <div class="form-group" >
                      <label class="col-sm-2 control-label" style="padding-top: 0 !important">
                        标题
                      </label>
                      <div class="col-sm-10">
                        <textarea readonly rows="1" class="form-control"><%= project.name%></textarea>
                      </div>
                    </div>
                    <div class="form-group" style="clear: both">
                      <label class="col-sm-3 control-label" style="padding-top: 0 !important;margin-top: -10px">
                        项目详情
                      </label>
                      <div class="col-sm-10" style="margin-left: 16.66666667%;">
                        <textarea readonly rows="15" class="form-control"><%= project.description%></textarea>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-sm-12" align="right" style="margin-top: 3%;">
                        <%= link_to '编辑此项目', projects_edt_path+'?'+'edt='+session[:project_id],class: 'btn btn-success btn-sm'%>
                      </div>
                    </div>
                    <% break %>
                <%end%>
            <%end%>
          </div>
          <div style="float: left;width: 60%;padding-left: 2.5%;padding-right: 2.5%">
            <%= form_for :status_add, url: projects_add_status_handle_path do |f| %>
            <div class="panel panel-primary project-panel">
              <div class="panel-heading" style="font-size: inherit !important;padding-top: 4px;padding-bottom: 4px">
                <div class="panel-title" align="center" style="font-weight: bold">
                  已有状态
                </div>
              </div>
              <div class="panel-body" style="padding: 5px;overflow-y: scroll;height: 150px !important">
                <table class="table index-show table-hover">
                  <tbody>
                  <% @status.each do |r| %>
                          <tr class="bg-warning">
                            <td style="width: 40%">
                              <%=  r.status %>
                            </td>
                            <td style="width: 40%;font-size: 12px !important;">
                              <%= r.created_at%>
                            </td>
                            <td style="vertical-align: middle;font-size:12px !important;text-align: center; width: 20%;text-decoration: underline" class="article-modify">
                              <%= link_to '删除', projects_add_status_path+'?del_status_id='+r.id.to_s %>
                            </td>
                          </tr>
                  <%end%>
                  </tbody>
                </table>
              </div>
            </div>
            <%end%>
            <%= form_for :status_add, url: projects_add_status_handle_path do |f| %>
            <div class="panel panel-primary project-panel" style="margin-top: 15px">
              <div class="panel-heading" style="font-size: inherit !important;padding-top: 4px;padding-bottom: 4px">
                <div class="panel-title" align="center" style="font-weight: bold">
                  添加状态
                </div>
              </div>
              <div class="panel-body" style="padding: 5px;">
                <%= f.text_area :status, rows: '4', class:'form-control'%>
              </div>
              <div class="form-group" style="margin-bottom: 8px">
                <div class="col-sm-12" align="right" style="padding-right: 0">
                  <%= f.submit('保存状态', class:'btn btn-success btn-sm')%>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/projects/edt.html.erb
<%= render '/welcome/nav'%>

<div class="container" style="min-height: 390px">
  <h2 align="center">编辑</h2>
  <div class="toMiddle" style="height: 4px;margin-bottom: 10px;margin-top: -5px"></div>
  <div style="width: 95%;float: right;margin-right: 2.5%">
    <ul class="nav nav-tabs nav-justified">
      <li role="presentation" class="active"><a href="">项目</a></li>
      <li role="presentation"><a href="../articles/modify">文章</a></li>
      <li role="presentation"><a href="../notices/modify">通知</a></li>
    </ul>
    <div style="width:100%; border: solid #ddd 1px;border-top: none;height: 500px">
      <%= form_for :projects_edt, url: :projects_edt_handle do |f| %>
          <div class="panel-body">
            <form class="form-horizontal" role="form">
              <div style="float: left;width: 75%">
                <div class="form-group" >
                  <label class="col-sm-2 control-label">标题</label>
                  <div class="col-sm-10">
                    <%= f.text_field  :title, :value => @project.name, class: 'form-control' %>
                  </div>
                </div>
                <div class="form-group" style="clear: both">
                  <label class="col-sm-2 control-label text-top">项目详情</label>
                  <div class="col-sm-10" style="margin-top: 10px">
                    <%= f.text_area  :description, :value => @project.description , rows:15, class: 'form-control'%>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-12" align="right" style="margin-top: 3%;padding-left: 20%">
                    <%= f.submit('保存修改', class:'btn btn-success btn-sm') %>
                  </div>
                </div>
              </div>
              <div style="float: left;width: 25%;padding-left: 2.5%;padding-right: 2.5%">
                <div class="panel panel-primary project-panel">
                  <div class="panel-heading" style="font-size: inherit !important;padding-top: 4px;padding-bottom: 4px">
                    <div class="panel-title" align="center" style="font-weight: bold">
                      项目状态
                    </div>
                  </div>
                  <div class="panel-body" style="padding: 5px;overflow-y: scroll;height: 125px !important">
                    <table class="table index-show table-hover">
                      <tbody>
                      <% @status.each do |r| %>
                          <tr class="bg-warning" align="center">
                            <td>
                              <%=  r.status %>
                            </td>
                          </tr>
                      <%end%>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-12" align="right" style="margin-top: -5%;padding-right: 0">
                    <%= link_to '添加状态', projects_add_status_path+'?'+'add='+@project.id.to_s,class: 'btn btn-success btn-sm',style: 'width: auto !important;'%>
                  </div>
                </div>
                <div class="panel panel-primary project-panel" style="margin-top: 15px">
                  <div class="panel-heading" style="font-size: inherit !important;padding-top: 4px;padding-bottom: 4px">
                    <div class="panel-title" align="center" style="font-weight: bold">
                      项目成员
                    </div>
                  </div>
                  <div class="panel-body" style="padding: 5px;overflow-y: scroll;height: 125px !important">
                    <table class="table index-show table-hover">
                      <tbody>
                      <% @members_all.each do |m| %>
                          <% if @map[m.id] == 'yes' %>
                              <tr class="bg-warning">
                                <td>
                                  <%= m.name%>
                                </td>
                              </tr>
                          <% end%>
                      <%end%>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-12" align="right" style="margin-top: -5%;padding-right: 0">
                    <%= link_to '添加成员', projects_add_members_path+'?project_id='+@project.id.to_s,class: 'btn btn-success btn-sm',style: 'width: auto !important;'%>
                  </div>
                </div>
              </div>
            </form>
          </div>
      <%end%>
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/projects/index.html.erb
<%= render '/welcome/nav'%>

<div class="container">
  <h3 align="center">项目列表</h3>
  <div style="margin-bottom: 5px">
    <ol class="breadcrumb">
      <li><a href="/">主页</a></li>
      <li class="active">项目</li>
    </ol>
  </div>
  <div class="toRight" style="height: 4px;margin-top: -10px"></div>
  <div class="row">
    <div class="col-xs-12">
      <table class="table index-show" style="margin-bottom: 10px !important;">
        <thead style="">
        <tr style="line-span: 3">
          <th style="width: 50%">项目名称</th>
          <th style="width: 50%">项目最新状态</th>
        </tr>
        </thead>
      </table>
      <hr style="border:none;border-top:2px dotted rgba(135, 135, 135, 1);margin-bottom: 3px;margin-top: -10px">
      <table class="table index-show table-hover bg-warning">
        <tbody>
        <% @i = 0 %>
        <% @projects.each do |a| %>
              <% @i = a.id %>
              <%params[:id] = @i%>
            <tr>
              <td style="width: 50%">
                <%= link_to a[:name], projects_path + '/' + @i.to_s %>
              </td>
              <td style="width: 50%">
                <%= @status_dict[@i]%>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <hr style="border:none;border-top:2px solid black;margin-bottom: 3px;margin-top: -20px">
    </div>


  </div>
</div>

<%= render 'welcome/footer' %>

app/views/projects/modify.html.erb
<%= render '/welcome/nav'%>

<div class="container">
  <h2>修改项目</h2>
  <div class="toRight" style="height: 4px"></div>
  <div class="row">
    <div class="col-xs-12">
      <table class="table index-show table-hover" style="vertical-align: middle">
        <tbody>
        <% @projects.each do |r|%>
            <tr class="bg-warning">
              <td style="width: 65%">
                <strong>&bull;&nbsp;</strong><%= r.name %>
              </td>
              <td style="font-size: 14px;text-align: center; width: 5%;text-decoration: underline" class="article-modify">
                <%= link_to '编辑', projects_edt_path+'?'+'edt='+r.id.to_s%>
              </td>
              <td style="font-size: 14px;text-align: center; width: 5%;text-decoration: underline" class="article-modify">
                <%= link_to '删除', projects_modify_path+'?'+'del='+r.id.to_s%>
              </td>
              <td style="font-size: 14px;text-align: center; width: 12%;text-decoration: underline" class="article-modify">
                <%= link_to '添加状态', projects_add_status_path+'?'+'add='+r.id.to_s%>
              </td>
              <td style="font-size: 14px;text-align: center; width: 13%;text-decoration: underline" class="article-modify">
                <%= link_to '添加成员', projects_add_members_path+'?project_id='+r.id.to_s%>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/projects/my_projects.html.erb
<%= render 'welcome/nav' %>

<div class="container" style="position:relative;min-height: 390px">

  <div align="center" style="margin-bottom: 20px">
    <h1>
      我的项目
    </h1>
  </div>

  <div class="panel panel-info " style="width: 25%;float: left">

    <div class="panel-heading">
      <h3 class="panel-title" align="center" style="font-weight: bold">
        项目名称
      </h3>
    </div>

    <div class="panel-body">
      <% @my_projects.each do |p| %>
          <div class="list-group-item">
            <%= link_to p[:name], projects_path+'/'+p.id.to_s %>
          </div>
      <% end %>
    </div>

  </div>

  </div>
  <!--<div class="panel panel-primary" style="width: 70%;margin-left:5%;float: left">-->
  <!--<div class="panel-heading">-->
  <!--<h3 class="panel-title" align="center" style="font-weight: bold">-->
  <!--详细内容-->
  <!--</h3>-->
  <!--</div>-->
  <!--<div class="panel-body" style="color: black">-->
  <!--<textarea rows="20" readonly="readonly" placeholder="这是项目的详细内容..." style="width: 100%;border-radius: 5px;border-color: #2aabd2">-->

  <!--</textarea>-->
  <!--</div>-->
  <!--</div>-->
  <!--</div>-->

  <%= render 'welcome/footer' %>
  <!--<h1>these are your projects.</h1>-->
  <!--<div class="container-fluid">-->
  <!--<div class="row-fluid">-->
  <!--<div class="col-xs-12">-->
  <!--<table class="table">-->
  <!--<thead>-->
  <!--<tr>-->
  <!--<th>-->
  <!--name-->
  <!--</th>-->
  <!--<th>-->
  <!--description-->
  <!--</th>-->

  <!--</tr>-->
  <!--</thead>-->
  <!--<tbody>-->

  <!--</tbody>-->
  <!--</table>-->
  <!--</div>-->
  <!--</div>-->
  <!--</div>-->

app/views/projects/new.html.erb
<%= render '/welcome/nav'%>

<div class="container" style="min-height: 390px">
  <h2 align="center">发布</h2>
  <div class="toMiddle" style="height: 4px;margin-bottom: 10px;margin-top: -5px"></div>
  <div style="width: 95%;float: right;margin-right: 2.5%">
    <ul class="nav nav-tabs nav-justified">
      <li role="presentation" class="active"><a href="../projects/new">项目</a></li>
      <li role="presentation"><a href="../articles/new">文章</a></li>
      <li role="presentation"><a href="../notices/new">通知</a></li>
    </ul>
    <div style="width:100%; border: solid #ddd 1px;border-top: none;height: 500px">
      <%= form_for :project, url: :projects do |f| %>
        <div class="panel-body">
          <form class="form-horizontal" role="form">
            <div class="form-group">
              <label class="col-sm-1 control-label">标题</label>
              <div class="col-sm-11" style="padding-left: -20px">
                <%= f.text_field(:title, class: 'form-control')%>
              </div>
            </div>
            <div class="form-group" style="clear: both">
              <label class="col-sm-2 control-label" style="margin-bottom: -40px;margin-top: 5px">项目详情</label>
              <div class="col-sm-11" style="margin-left:8.33333333%;margin-top: 10px">
                <%= f.text_area(:text, rows:15, class: 'form-control')%>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-12" align="right" style="margin-top: 3%;padding-left: 50%">
                <%= f.submit('保存项目', class:'btn btn-success btn-sm') %>
              </div>
            </div>
          </form>
        </div>
      <%end%>
    </div>
  </div>
</div>

<%= render 'welcome/footer' %>

app/views/projects/show.html.erb
<%= render '/welcome/nav'%>

<div class="container" style="position:relative;min-height: 390px">
  <ol class="breadcrumb">
    <li><a href="/">主页</a></li>
    <li><a href="/projects">项目列表</a></li>
    <li class="active"><%= @project[:name]%></li>
  </ol>
  <div align="center">
    <h1>
      <%= @project[:name]%>
    </h1>
  </div>
  <div align="right">
    <label class="show-date">
      创建日期:<%= %><br>浏览量:
    </label>
  </div>
  <table class="table index-show">
    <thead>
      <tr style="">
        <td style="width: 75%;font-weight: bold">项目详情</td>
        <td style="width: 25%;font-weight: bold">成员</td>
      </tr>
    </thead>
  </table>
  <div style="width:65%; min-height: 300px" class="project-show">
    <p style="text-indent: 2em"> <%= @project[:description]%></p>
  </div>
  <div style="width: 20%;margin-left: 10%;min-height: 200px;float: left;position: relative">
    <div style="width: 100%;min-height: 100px" class="project-show">
      <% @members.each do |m|%>
          <p style="margin-left: 20%"><%= m.name%></p>
      <%end%>
    </div>
    <div style="width: 40%;position:absolute; left: 30%;bottom: 40px">
      <% if session[:ut]!=nil%>
          <button class="btn btn-success" style="width: 100%">加入</button>
      <% else %>
          <a href="../memberships/login" role="button" class="btn btn-success" style="width: 100%">加入</a>
      <% end%>

  </div>
  </div>
</div>


<%= render 'welcome/footer' %>